setfenv(1, require "sysapi-ns")

ffi.cdef [[
  DWORD GetLastError();

  void SetLastError(
    DWORD dwErrCode
  );
]]

S_OK = 0
ERROR_SUCCESS = 0
ERROR_INVALID_FUNCTION = 1
ERROR_FILE_NOT_FOUND = 2
ERROR_PATH_NOT_FOUND = 3
ERROR_TOO_MANY_OPEN_FILES = 4
ERROR_ACCESS_DENIED = 5
ERROR_INSUFFICIENT_BUFFER = 122
ERROR_MORE_DATA = 234
ERROR_NO_MORE_ITEMS = 259
